name: CI

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - edited
env:
  node_version: "14.x"

jobs:
  test:
    name: Test Module
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: npm test
        run: |
          npm run coverage

      - name: Upload coverage to Codecov
        if: ${{ matrix.node-version == env.node_version }} # only upload coverage from node 14
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  audit:
    name: Audit Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: npm audit
        run: npm audit --audit-level=critical

  lint:
    name: Lint Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run lint
